version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker info
          docker build -f Dockerfile -t texastribune/checkout:dev .
          docker run -it --rm --workdir=/app --entrypoint=/app/circle.sh
branches:
  ignore:
    - master
